# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TextArea' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'ReactorKit'

  target 'TextAreaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TextAreaUITests' do
    # Pods for testing
  end

end
